--- 
author: "Espoir Murhabazi Buzina"
description: |
    My personal website
    I always write  about problems I am facing in my career and the solution I found after googling
    and sometimes the lessons I have learned.
    PS: My grammar is not the best,  so those post may contain grammar mistakes and typos 
    please help me to fix them by making a pull request with corrections
email: espoir.mur@gmail.Com
plugins: 
  - jekyll-twitter-plugin
show_excerpts: true
theme: minima
title: "Espoir Murhabazi, Software Engineer and  Aspiring Machine Learning Engineer"
