title: Espoir Murhabazi, Aspiring Machine Learning Engineer
author: Espoir Murhabazi Buzina 
email: espoir.mur@gmail.Com
description: My Blog ,and random stuffs I write about

# social links
#twitter_username: @EspyMur
#github_username:  @espoirMur
#stackoverflow_username: espoir-murhabazi
#medium_username: @EspyMur
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima 
plugins: ['jekyll-twitter-plugin']
